Repository k-roffle/knitting-frontend, pull requests merged in 2021-08, with the labels that each got.

#73 [Design] Header와 Footer 컴포넌트 추가
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/index.ts
  src/dumbs/Layout/index.tsx
  src/dumbs/Logo/index.tsx
  src/dumbs/RequiredSelect/index.tsx
  src/dumbs/index.tsx
  src/pages/CreateDesign/Detail/index.tsx
  src/pages/CreateDesign/Pattern/index.tsx
  src/pages/CreateDesign/components/Footer/index.tsx
  src/pages/CreateDesign/components/Header/index.tsx
  src/pages/CreateDesign/components/StepProgressBar/index.tsx
  src/pages/CreateDesign/index.tsx
  src/pages/Login/index.tsx
  src/plugins/unitDecorator/unitDecorator.tsx
  src/themes/overrides.ts
Labels: Design

#83 fix: 도안 생성 API 요청이 정상적으로 이뤄지도록 수정
  src/pages/CreateDesign/Detail/index.tsx
  src/pages/CreateDesign/components/Footer/index.tsx
  src/pages/CreateDesign/recoils.ts
  src/pages/CreateDesign/types.ts
  src/plugins/unitDecorator/unitDecorator.tsx
  src/utils/auth.ts
Labels: Bug / Function, High

#78 [Design] 내 정보 & 내가 만든 도안 리스트 껍데기
  package.json
  src/App.tsx
  src/components/Ellipsis/index.tsx
  src/components/index.ts
  src/pages/CreateDesign/Detail/index.tsx
  src/pages/MyInformation/components/DesignItem/index.tsx
  src/pages/MyInformation/components/InformationTabPanel/index.tsx
  src/pages/MyInformation/components/InformationTabs/index.tsx
  src/pages/MyInformation/components/MyProfile/index.tsx
  src/pages/MyInformation/index.tsx
  src/routers/MyInformationRouter/index.tsx
  src/styles/constants.ts
  src/themes/overrides.ts
  src/utils/renderText.ts
  yarn.lock
Labels: Feat, Design

#80 [Design] CircularProgress 컴포넌트 중앙정렬 하도록
  src/pages/LoginRedirected/index.tsx
Labels: Design

#89 [Feat] 헤더 메뉴 (내 정보, 로그아웃) 구현
  .eslintrc.json
  src/App.tsx
  src/components/Header/index.tsx
  src/constants/errors.ts
  src/constants/path.ts
  src/pages/CreateDesign/Pattern/index.tsx
  src/pages/CreateDesign/components/Footer/index.tsx
  src/pages/LoginRedirected/index.tsx
  src/routers/LoginRouter/index.tsx
  src/routers/MyInformationRouter/index.tsx
  src/utils/auth.ts
  src/utils/route.tsx
Labels: Feat, Bug / Function, Medium, Refactor

#95 feat: API 응답 스펙 변경 적용
  src/pages/LoginRedirected/index.tsx
  src/utils/auth.ts
Labels: Bug / Function, High
