Repository k-roffle/knitting-frontend, pull requests merged in 2021-03, with the labels that each got.

#7 [Docs] PR, Issue 템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 [Feat] 초기 router 세팅
  .eslintignore
  .eslintrc.json
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/CreateDesign/Detail/index.tsx
  src/pages/CreateDesign/Pattern/index.tsx
  src/pages/CreateDesign/Review/index.tsx
  src/pages/CreateDesign/index.tsx
  src/pages/Designs/index.tsx
  src/pages/Error404/index.tsx
  src/pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#8 [Feat] 새로운 도안 작성하기 - 프레임 구현
  .eslintrc.json
  src/App.tsx
  src/dumbs/Button/index.tsx
  src/pages/CreateDesign/components/Container/index.tsx
  src/pages/CreateDesign/components/Footer/index.tsx
  src/pages/CreateDesign/components/Header/index.tsx
  src/pages/CreateDesign/index.tsx
  src/pages/CreateDesign/recoils.ts
  src/pages/CreateDesign/types.ts
Labels: enhancement

#18 [Fix] 이슈 추가 시 이슈 템플릿이 나올 수 있도록 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation, Low, Other bug

#14 [Feat] 새로운 도안 작성하기 - 기본 정보 입력 프레임
  src/assets/designs/knit.png
  src/dumbs/Layout/index.tsx
  src/globalStyles.ts
  src/index.tsx
  src/pages/CreateDesign/Detail/index.tsx
  src/pages/CreateDesign/components/Container/index.tsx
Labels: Feat, High

#15 [Feat] 공통으로 쓰이는 글로벌 테마 정의
  src/pages/CreateDesign/index.tsx
  src/themes/index.ts
  src/themes/overrides.ts
  src/themes/palatte.ts
  src/themes/typography.ts
Labels: Design, Feat, High

#21 [Refactor] 스타일 주입 방법 리팩토링
  src/dumbs/Button/index.tsx
  src/pages/CreateDesign/components/StepProgressBar/index.tsx
  src/themes/index.ts
  src/themes/overrides.ts
  src/themes/zIndex.ts
Labels: Low, Refactor
