Repository k-roffle/knitting-frontend, pull requests merged in 2022-03, with the labels that each got.

#154 createDesign validation 방식 변경
  src/components/ImageFileUploader/ImageFileUploader.css.ts
  src/components/ImageFileUploader/index.tsx
  src/dumbs/InlineInput/index.tsx
  src/dumbs/InputWithLabel/index.tsx
  src/pages/CreateDesign/Cover/index.tsx
  src/pages/CreateDesign/Outline/index.tsx
  src/pages/CreateDesign/Pattern/index.tsx
  src/pages/CreateDesign/Review/index.tsx
  src/pages/CreateDesign/atom.ts
  src/pages/CreateDesign/components/Footer/Footer.css.ts
  src/pages/CreateDesign/components/Footer/hooks/useStepController.ts
  src/pages/CreateDesign/components/Footer/index.tsx
  src/pages/CreateDesign/hooks/useInvalidOutline.ts
  src/pages/CreateDesign/index.tsx
  src/pages/CreateDesign/utils.ts
  src/themes/overrides.ts
Labels: Feat, Refactor

#153 [Feat] 도안 임시저장 기능 추가
  src/hooks/useGet.ts
  src/hooks/usePost.ts
  src/pages/CreateDesign/atom.ts
  src/pages/CreateDesign/components/Footer/hooks/useSaveDesign.ts
  src/pages/CreateDesign/components/Footer/hooks/useStepController.ts
  src/pages/CreateDesign/types.ts
  src/pages/CreateProduct/components/Footer/hooks/useSaveProduct.ts
  src/pages/CreateProduct/components/Footer/hooks/useStartSale.ts
  src/pages/CreateProduct/types.ts
  src/utils/requestType.ts
  src/utils/requests.ts
Labels: Feat

#155 [Feat] 상품 구성하기 화면에서 가격 아코디언 추가
  src/dumbs/Accordion/Accordion.css.ts
  src/dumbs/Accordion/index.tsx
  src/pages/CreateProduct/Package/Package.css.ts
  src/pages/CreateProduct/Package/index.tsx
  src/pages/CreateProduct/SelectDesigns/index.tsx
  src/pages/CreateProduct/components/Footer/hooks/useSaveProduct.ts
  src/pages/CreateProduct/recoils.ts
  src/pages/CreateProduct/types.ts
  src/pages/MyInformation/components/DesignItem/index.tsx
Labels: Feat

#156 [Fix] Pre-commit node_modules 가르키는 문제 수정
  .githooks/pre-commit
  .github/PULL_REQUEST_TEMPLATE.md
  src/pages/CreateDesign/components/Footer/hooks/useStepController.ts
  src/pages/CreateProduct/Package/index.tsx
Labels: Other bug, Documentation

#157 [Feat] 도안 카드 컴포넌트 수정
  src/pages/CreateProduct/types.ts
  src/pages/MyInformation/components/DesignItem/DesignItem.css.ts
  src/pages/MyInformation/components/DesignItem/index.tsx
  src/themes/palette.ts
Labels: Feat
